---
# tasks file for ansible-role-influxdb

- name: Download InfluxDB binary.
  get_url:
    url: "https://dl.influxdata.com/influxdb/releases/influxdb-{{ influxdb_version }}_linux_{{ influxdb_cpu_arch }}.tar.gz"
    dest: "/opt/influxdb-{{ influxdb_version }}_linux_{{ influxdb_cpu_arch }}.tar.gz"

- name: Extract InfluxDB binary.
  unarchive:
    src: "/opt/influxdb-{{ influxdb_version }}_linux_{{ influxdb_cpu_arch }}.tar.gz"
    dest: /opt/
    copy: False
    
- name: Create InfluxDB user.
  user:
    name: "{{ influxdb_user }}"
    state: present
    system: True

- block:

    - name: Ensure Systemd unit file is present.
      template:
        src: influxdb.service.j2
        dest: /usr/lib/systemd/system/influxdb.service

    - name: Ensure InfluxDB is enabled at boot.
      systemd:
        name: influxdb
        daemon_reload: True
        enabled: True

  when: ansible_service_mgr == 'systemd'

- name: Ensure sysv init script is present.
  template:
    src: influxdb.init.j2
    dest: /etc/init.d/influxdb
    mode: 0700  
  when: ansible_service_mgr == 'sysv'
  
- name: Set command options.
  template:
    src: influxdb.j2
    dest: /etc/default/influxdb
  register: influxdb_cmd_options

- name: Ensure InfluxDB configuration directory is present.
  file:
    path: /etc/influxdb
    state: directory

- name: Create InfluxDB configuration.
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
  register: influxdb_config

- name: Ensure InfluxDB paths are present.
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ influxdb_user }}"
    group: "{{ influxdb_group }}"
    recurse: True
    mode: u=rwX,g=rX,o=r
  with_items:
    - "{{ influxdb_meta_data_dir }}"
    - "{{ influxdb_data_dir }}"
    - "{{ influxdb_data_wal_dir }}"
    - "{{ influxdb_log_path }}"

- name: Restart InfluxbDB and enable InfluxDB at boot.
  service:
    name: influxdb
    state: restarted
    enabled: True
  when: "{{ influxdb_cmd_options | changed }} or {{ influxdb_config | changed }}"
