---
# tasks file for ansible-role-influxdb

- name: Include OS-specific variables.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: setup-Other.yml
  when: ansible_os_family != 'Debian' or ansible_os_family != 'RedHat'
  
- name: Set command options.
  template:
    src: influxdb.j2
    dest: /etc/default/influxdb
  register: influxdb_cmd_options

- name: Ensure InfluxDB configuration directory is present.
  file:
    path: /etc/influxdb
    state: directory

- name: Create InfluxDB configuration.
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
  register: influxdb_config

- name: Ensure InfluxDB paths are present.
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ influxdb_user }}"
    group: "{{ influxdb_group }}"
    recurse: True
    mode: u=rwX,g=rX,o=r
  with_items:
    - "{{ influxdb_meta_data_dir }}"
    - "{{ influxdb_data_dir }}"
    - "{{ influxdb_data_wal_dir }}"
    - "{{ influxdb_log_path }}"

- name: Restart InfluxDB and enable InfluxDB at boot.
  service:
    name: influxdb
    state: restarted
    enabled: True
  when: "{{ influxdb_cmd_options | changed }} or {{ influxdb_config | changed }}"
